# **Introduzione a NumPy**
## *Algebra Polinomi e Statistica*
Introduzione ed esercizi sulla classe **numpy** e i rispettivi moduli **linalg** e **polynomial**

## **Operazioni Fondamentali**

In [5]:
# Importazione dei moduli di interesse
import numpy as np
from numpy import linalg
import numpy.polynomial.polynomial as poly
import matplotlib.pyplot as plt

Gli **array** sono la struttura dati principale di NumPy:

- Rappresentano un generico *tensore*
- Sono composti da elementi *omogenei* 
- Possono essere sia monodimensionali, sia n-dimensionali

Possiamo valutarne le dimensioni mediante la proprietà `shape`


In [62]:
a = np.array([[1, 2, 3, 4, 5, 6],[1,0,0,0,0,0]])
a.shape

(2, 6)

Esistono diversi metodi per la creazione rapida di un array
- `ones` creo un array di tutti 1
- `zeros` creo un array di tutti 0
- `empty` creo un array non inizializzato
- `eye` creo la matrice identità

In [60]:
u = np.ones(shape=(3,3)) # creo un array di tutti 1
z = np.zeros(shape=(3,3)) # creo un array di tutti 0
e = np.empty(shape=(3,3)) # creo un array non inizializzato
i = np.eye(3) # creo la matrice identità

Il metodo `diag(x)` permette di:
- estrarre la diagonale se x è una matrice;
- ottenere una matrice diagonale con x diagonale se x è un vettore.

## **Algebra**

Per calcolare la **trasposta** di una matrice, usiamo la funzione `transpose`.

In [38]:
# Faccio una prova di transposta di una matrice rettangolare
m1 = np.array([[1,2,3],[4,5,6]])
np.transpose(m1)

array([[1, 4],
       [2, 5],
       [3, 6]])

Per calcolare l'**inversa** di una matrice, usiamo la funzione `inv` del package `linalg`.

In [39]:
# Uso linalg.inv(matrice) per verificare se una matrice è invertibile o no
# Una condizione necessaria e sufficiente è che la matrice sia innanzittutto
# quadrata e poi che il determinante sia diverso da zero

m2 = np.array([[1,0,0],[0,5,0],[0,0,3]])
linalg.inv(m2)

array([[1.        , 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.33333333]])

Se proviamo a calcolare l'inversa di una matrice rettangolare o di una matrice singolare, la funzione `inv` restituirà un errore di tipo `LinAlgError`. Uso di `try` and `except`

In [40]:
# Proviamo a gestire un'eccezione con il costrutto "try except as"
# Se sappiamo il tipo di errore che può presentarsi possiamo metterlo al posto di "Exception"
# Se l'errore è particolare, bisogna importare la libreria degli errori della classe specifica, ad esempio:
# import numpy.exception()

m3 = np.array([[1,2,3],[2,4,6],[5,2,12]])
try:
    linalg.inv(m3)
except Exception as e:
    print("Errore")

# Oppure
try:
    np.linalg.inv(m3)
except np.linalg.LinAlgError:
    print('Questo è ciò che accade se usiamo una matrice rettangolare!')

Errore
Questo è ciò che accade se usiamo una matrice rettangolare!


Usiamo la funzione `inner` per calcolare il prodotto **scalare** tra due vettori. Partiamo con un caso monodimensionale:

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.inner(a, b)

32

Vediamo cosa accade in un caso **multidimensionale**:

In [42]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[0, 1], [1, 0]])

np.inner(a, b)

array([[2, 1],
       [4, 3]])

In questo caso, la formulazione è del tipo:

$$
p = \left[
    \begin{array}{cc}
        a_1 * b_1 + a_2 * b_2 & a_1 * b_3 + a_2 * b_4 \\
        a_3 * b_1 + a_4 * b_2 & a_3 * b_3 + a_4 * b_4
    \end{array}
\right] = \\
=\left[
    \begin{array}{cc}
        1 * 0 + 2 * 1 && 1 * 1 + 2 * 0 \\
        3 * 0 + 4 * 1 && 3 * 1 + 4 * 0
    \end{array}
\right]
= \left[
    \begin{array}{cc}
        2 & 1 \\
        4 & 3
    \end{array}
\right]
$$


Il prodotto **esterno** viene calcolato mediante la funzione `outer`:

In [43]:
a = np.array([1, 2])
b = np.array([3, 4])

np.outer(a, b)

array([[3, 4],
       [6, 8]])

La funzione `matmul` ci permette di effettuare il **prodotto matriciale** tra due matrici.

In [44]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.matmul(a, b)

array([[19, 22],
       [43, 50]])

Per **elevare la matrice a potenza** utilizzare la funzione `matrix_power` del package `linalg`:

In [45]:
np.linalg.matrix_power(a, 5)

array([[1069, 1558],
       [2337, 3406]])

Per effettuare la **decomposizione ai valori singolari**. Tale processo è una tecnica di **riduzione della
dimensionalità**. Consiste nello scomporre la matrice iniziale in tre diverse sottomatrici e si basa sul concetto di *trasformazione lineare*

In [46]:
(u, s, v) = np.linalg.svd(a)
print('u:', u, '\ns:', s, '\nv:', v)

u: [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] 
s: [5.4649857  0.36596619] 
v: [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


Per calcolare **autovettori ed autovalori** di una matrice, usiamo la funzione `eig` del package `linalg`:

In [47]:
(w, v) = np.linalg.eig(a)
print('Autovalori:', w, '\nAutovettori:', v)

Autovalori: [-0.37228132  5.37228132] 
Autovettori: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Per calcolare la norma, usiamo la funzione `norm`:

In [48]:
np.linalg.norm(a)

5.477225575051661

Per calcolare *rango*, *determinante* e *traccia*, usiamo rispettivamente:

In [49]:
# Rango:
rank = np.linalg.matrix_rank(a)

# Determinante
det = np.linalg.det(a)

# Traccia
tr = np.trace(a)

print('Rango:', rank, '\nDeterminante:', det, '\nTraccia:', tr)

Rango: 2 
Determinante: -2.0000000000000004 
Traccia: 5


Per risolvere il seguente sistema di equazioni lineari:

$$
\begin{cases}
x_1 + 2 x_2 + 5 x_3 = y \\
2 x_1 + 2 x_2 + 3 x_3 = 3 y \\
2 x_1 + 2 x_2 + x_3 = 2 y
\end{cases}
$$

In [50]:
x = np.array([[1, 2, 2], [2, 2, 2], [5, 3, 1]])
y = np.array([1, 3, 2])

np.linalg.solve(x, y)

array([ 2.  , -3.75,  3.25])

## **Polinomi**

Per rappresentare un polinomio, usiamo un oggetto di classe `poly1d()`. Esso è caratterizzato da un vettore di coefficienti.

Per **sommare** due polinomi, usiamo la funzione `polyadd(p1, p2)`.

Per **sottrarre** due polinomi, usiamo la funzione `polysub(p1, p2)`.

Analogamente abbiamo `polymul(p1, p2)` (**moltiplicazione**), `polydiv(p1, p2)` (**divisione**) e `polypow(p, pow)` (**elevazione a potenza**).

Proviamo a considerare:
 


$$
\begin{cases}
c_1 = 2x + 1 \\
c_2 = x^2 + 3x + 2 \\
c_3 = x^2 + x
\end{cases}
$$

Allora:

In [68]:
c1 = np.poly1d((0, 2, 1))
c2 = np.poly1d((1, 3, 2))
c3 = np.poly1d((1, 1, 0))
p1 = poly.polyadd(c1, c2) # In uscita ho un array
p2 = poly.polyadd(c1, c3)

print('Somma di c1 e c2:\n', np.poly1d(p1), '\nSomma di c1 e c3:\n', np.poly1d(p2))

Somma di c1 e c2:
    2
3 x + 4 x + 2 
Somma di c1 e c3:
  
3 x + 2


In [69]:
print('Sottrazione di c1 a c2:\n', np.poly1d(poly.polysub(c2, c1)))

Sottrazione di c1 a c2:
     2
-1 x + 2 x + 2


In [70]:
p_mul = poly.polymul(c1, c3)[-1::-1]
p_div = poly.polydiv(c3, c1)[-1::-1]
print(
    'Prodotto tra c1 e c3:\n',
    np.poly1d(p_mul),
    '\nQuoziente tra c3 e c1:\n',
    np.poly1d(p_div[0]),
    '\nResto tra c3 e c1:\n',
    np.poly1d(p_div[1]))

Prodotto tra c1 e c3:
    2
1 x + 3 x + 2 
Quoziente tra c3 e c1:
  
-1 
Resto tra c3 e c1:
  
1


In [71]:
p_pow = poly.polypow(c1, 2)[-1::-1]
print('c1 al quadrato è pari a:\n', np.poly1d(p_pow))

c1 al quadrato è pari a:
    2
1 x + 4 x + 4


Valutiamo i valori assunti dal polinomio `c1` in  $x =0, 1, 2$:

In [73]:
vals = poly.polyval([0, 1, 2], c1)

print(
    'Per x = 0, c1 vale:', vals[0],
    '\nPer x = 1, c1 vale:', vals[1],
    '\nPer x = 2, c1 vale:', vals[2])

Per x = 0, c1 vale: 2.0 
Per x = 1, c1 vale: 3.0 
Per x = 2, c1 vale: 4.0


Per calcolare la **derivata** e l'**integrale** di un polinomio:

In [74]:
p_der_one = poly.polyder(c1.coeffs[-1::-1])
print('La derivata di c1 è:', np.poly1d(p_der_one))

p_int = poly.polyint(c1.coeffs[-1::-1])[-1::-1]
print('L\'integrale indefinito di c1 è:', np.poly1d(p_int))

La derivata di c1 è:  
2
L'integrale indefinito di c1 è:    2
1 x + 1 x


## **Statistica**

Il **k – percentile** di un vettore 𝑉 di lunghezza 𝑁 è definito come il valore pari a $\frac{k}{100}$
calcolato a partire da una copia
ordinata di 𝑉.
Ad esempio considerati $100$ numeri ordinati, il *10-percentile* è 10, ossia tutti gli elementi sotto al 10. Ossia in generale il *k-percentile* è il $k-percento$ degli elementi ordinati sul vettore 

Esistono diversi modi di calcolare il *k – percentile* in NumPy ci mette a disposizione la funzione `percentile()`

Il **quantile** è sostanzialmente analogo al percentile con valori normalizzati. Per calcolarlo ci offre la funzione
`quantile()`

In [81]:
v = np.array([1,5,6,7])
print(np.percentile(v,50))
print(np.quantile(v,.5))

5.5
5.5


La **media** degli elementi di un array può essere calcolata in due modi.
- Il primo prevede il calcolo puramente aritmetico mediante la funzione `mean()`
- Il secondo usa una media pesata mediante la funzione `average()`
Inoltre esistono anche delle funzioni per calcolare **deviazione standard** e **varianza**: `std()` `var()`

In [83]:
a = np.array([5, 12, 22, 3])

print(np.mean(a))
print(np.average(a, weights=[3, 1, 1, 3]))
print(np.std(a))
print(np.var(a))

10.5
7.25
7.433034373659253
55.25


Ad esempio per calcolare il *percentile* ed il *quantile*:

In [7]:
rng = np.random.default_rng(42) # Generatore casuale
c = rng.integers(low=0, high=100, size=50)
print(c)
print('25-percentile di c:', np.percentile(c, 25))
print('75-quantile di c:', np.quantile(c, .75))

[ 8 77 65 43 43 85  8 69 20  9 52 97 73 76 71 78 51 12 83 45 50 37 18 92
 78 64 40 82 54 44 45 22  9 55 88  6 85 82 27 63 16 75 70 35  6 97 44 89
 67 77]
25-percentile di c: 35.5
75-quantile di c: 77.0


Vediamo la matrice di covarianza:

In [8]:
x_corr = np.array([[1, 2, 3], [4, 5, 6]])
print('x_1:\n', x_corr, '\n')
print('Matrice di covarianza:\n', np.cov(x_corr))
x_anticorr = np.array([[1, 2, 3], [-1, -2, -3]])
print('\nx_2:\n', x_anticorr, '\n')
print('Matrice di covarianza:\n', np.cov(x_anticorr))

x_1:
 [[1 2 3]
 [4 5 6]] 

Matrice di covarianza:
 [[1. 1.]
 [1. 1.]]

x_2:
 [[ 1  2  3]
 [-1 -2 -3]] 

Matrice di covarianza:
 [[ 1. -1.]
 [-1.  1.]]
